### ISSUE TITLE
`IGNITION_LOCAL_SITES_PATH` environment variable does not work

### ISSUE THREAD

**Issue by ridiks10** [spatie/laravel-ignition#21]
Does not work IGNITION_LOCAL_SITES_PATH  in "facade/ignition": "^2.5" everything is working

**Comment by godforhire** [comment]
I think I run into the same problem. PHPStorm wants to open the remote file instead of the local file (Cannot create /home/vagrant/code/newsite/resources/views/... etc).

In .env

IGNITION_REMOTE_SITES_PATH=/home/vagrant/code/newsite
IGNITION_LOCAL_SITES_PATH=/Users/<username>/Projects/Sites/newsite

In config/ignition.php

    'remote_sites_path' => env('IGNITION_REMOTE_SITES_PATH', base_path()),
    'local_sites_path' => env('IGNITION_LOCAL_SITES_PATH', ''),

Laravel 8.80.0, changed facade/ignition to spatie/laravel-ignition ^ 1.0
Same configuration was working before the upgrade.

**Comment by hylke94** [comment]
> I think I run into the same problem. PHPStorm wants to open the remote file instead of the local file (Cannot create /home/vagrant/code/newsite/resources/views/... etc).
> 
> In .env
> 
> IGNITION_REMOTE_SITES_PATH=/home/vagrant/code/newsite IGNITION_LOCAL_SITES_PATH=/Users/username/Projects/Sites/newsite
> 
> In config/ignition.php
> 
> ```
> 'remote_sites_path' => env('IGNITION_REMOTE_SITES_PATH', base_path()),
> 'local_sites_path' => env('IGNITION_LOCAL_SITES_PATH', ''),
> ```
> 
> Laravel 8.80.0, changed facade/ignition to spatie/laravel-ignition ^ 1.0 Same configuration was working before the upgrade.

Trying the new Ignition frontend. Looks awesome! But the remote path is not replaced in place indeed..

**Comment by hailwood** [comment]
Same issue here using Lando (wrapper around docker).

Project sits at `/home/matthew/Projects/my-project/app` on my local system.
So full path to the home controller would be 
```
/home/matthew/Projects/my-project/app/app/Http/Controllers/HomeController.php
```

In the docker container it sits at `/app`
So full path to the home controller would be
```
/app/app/Http/Controllers/HomeController.php
```

My compiled config file after env() replacements contains
```
"remote_sites_path" => "/app",
"local_sites_path" => "/home/matthew/Projects/my-project/app",
```

But the link to edit is still

```
phpstorm://open?file=/app/app/Http/Controllers/HomeController.php&line=6
```

**Comment by telkins** [comment]
Same issue here.  It worked great before upgrading from `facade/ignition` to `spatie/laravel-ignition`.

Now, after upgrading, even if I hard-code the values in the config file (which doesn't seem to want to be publishable, btw), it still doesn't seem to work.

I make the changes (to the config/ignition.php file in the vendor folder), clear the config cache, and retry.  I get the same message each time.

I'm happy to provide more details, but it seems like several others have covered all the bases.  If you'd like me to share, please let me know and I'll be happy to do so.

**Comment by anhofmann** [comment]
I have the same problem: this is in my `config/ignition.php`:

```php
return [
    'remote_sites_path' => '/foo/bar',
    'local_sites_path' => '/baz/qux',
  // everything else is still in the array
];
```
This is how the link lands in my browser (vivaldi, but it is the same on all blink engines and on firefox):
`phpstorm://open?file=%2Fvar%2Fwww%2Fhtml%2Fresources%2Fviews%2Fcomponents%2Fsection.blade.php&line=3`

So not only gets everything ignored that is in my ignition config, but also the path is urlencoded and doesn't work. I could enter manually in my browser `phpstorm://open?file=/srv/projectA/resources/views/components/section.blade.php&line=3` and this will open in PHPStorm.

I'm running PHPStorm on Linux and Laravel with sail. Furthermore, I'm happy to provide more information.

**Comment by freekmurze** [comment]
We'll try to look at this soon. If you need this fixed fasted, we'd appreciate a PR.

**Comment by justmd5** [comment]
> Same issue here. It worked great before upgrading from `facade/ignition` to `spatie/laravel-ignition`.
> 
> Now, after upgrading, even if I hard-code the values in the config file (which doesn't seem to want to be publishable, btw), it still doesn't seem to work.
> 
> I make the changes (to the config/ignition.php file in the vendor folder), clear the config cache, and retry. I get the same message each time.
> 
> I'm happy to provide more details, but it seems like several others have covered all the bases. If you'd like me to share, please let me know and I'll be happy to do so.

same with me

**Comment by Josh-G** [comment]
I believe this is fixed now by a change made to `@flareapp/ignition-ui` in 3.2.0, but I cannot find a repo for this npm package. Is it private?

**Comment by AlexVanderbist** [comment]
@Josh-G you can find the Ignition UI package [here](https://github.com/spatie/ignition-ui)

**Comment by Josh-G** [comment]
That's a 404 for me.

**Comment by AlexVanderbist** [comment]
@Josh-G my bad, try again now :)

**Comment by AlexVanderbist** [comment]
Hey all, I was just testing this out and it seems to work alright for me (like @Josh-G said). Can anyone confirm that this issue still exists on the latest version of the package?

**Comment by justmd5** [comment]
> Hey all, I was just testing this out and it seems to work alright for me (like @Josh-G said). Can anyone confirm that this issue still exists on the latest version of the package?

it's ok for me now !

**Comment by AlexVanderbist** [comment]
Thanks @justmd5 and @Josh-G for checking this.

I'm gonna close this issue for as the root problem seems to have been fixed. Feel free to open a new issue and link to this one if the issue would re-occur.

Thanks everyone!
